sudo: required
language: generic
services:
  - docker
env:
  global:
    - VERSION=0.1.0
before_install:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

deploy:
  provider: script
  script: bash ./build_and_push.sh
  on:
    branch: main
