## ------------------------------------------------------
## Zookeeper
## ------------------------------------------------------
cp-zookeeper:
  enabled: true
  servers: 1
  image: confluentinc/cp-zookeeper
  imageTag: 6.1.0
  prometheus:
    jmx:
      enabled: false
  persistence:
    enabled: true
    dataDirSize: 1Gi
    dataLogDirSize: 1Gi

## ------------------------------------------------------
## Kafka
## ------------------------------------------------------
cp-kafka:
  enabled: true
  brokers: 3
  image: confluentinc/cp-enterprise-kafka
  imageTag: 6.1.0
  prometheus:
    jmx:
      enabled: false
  persistence:
    enabled: true
    size: 1Gi
    disksPerBroker: 1

## ------------------------------------------------------
## Kafka Connect
## ------------------------------------------------------
cp-kafka-connect:
  enabled: true
  image: d0rka/confluent-debezium-outbox-image
  imageTag: 0.1.1
  prometheus:
    jmx:
      enabled: false
  configurationOverrides:
    key.converter.schemas.enable: false
    key.converter: org.apache.kafka.connect.json.JsonConverter
    value.converter.schemas.enable: false
    value.converter: org.apache.kafka.connect.json.JsonConverter
  customEnv:
    CONNECT_REST_PORT: 8083
    CONNECT_KEY_CONVERTER_SCHEMAS_ENABLE: false
    CONNECT_VALUE_CONVERTER_SCHEMAS_ENABLE: false
    DB_HOST: postgres-cis
    DB_PORT: 5432
    DB_USERNAME: postgres
    DB_PASSWORD: my_pgpassword
    DB_NAME: posts
    DB_SERVERNAME: posts

## ------------------------------------------------------
## Schema Registry
## ------------------------------------------------------
cp-schema-registry:
  enabled: false

## ------------------------------------------------------
## REST Proxy
## ------------------------------------------------------
cp-kafka-rest:
  enabled: false

## ------------------------------------------------------
## KSQL Server
## ------------------------------------------------------
cp-ksql-server:
  enabled: false

## ------------------------------------------------------
## Control Center
## ------------------------------------------------------
cp-control-center:
  enabled: false
