name: Release Charts

on:
  push:
    branches:
      - main

env:
  VERSION: 0.1.1

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push
        id: docker_build_backend
        uses: docker/build-push-action@v2
        with:
          context: ./kafka-connect
          file: ./kafka-connect/Dockerfile
          push: true
          tags: |
            d0rka/confluent-debezium-outbox-image:latest
            d0rka/confluent-debezium-outbox-image:${{ github.sha }}
            d0rka/confluent-debezium-outbox-image:${{ env.VERSION }}
